### PR TITLE
Custom dimensions of the map

### PR DESCRIPTION
**Pull request by rodrigo-ldc**
Map CSS as a block to allow interaction when routing. The user can now specify the height and width of the map's pane when running the server

>geeservermap --width 500 --height 800

### CODE REVIEW

**Review by 12rambau — COMMENTED** [review]
Why does the templates use the html extension when they are in fact jinja2 files ?

**Comment by rodrigo-ldc** [comment]
sorry @12rambau, can you explain a bit more? `flask` uses `jinja2` yes (https://flask.palletsprojects.com/en/2.3.x/templating/)... what other extension could it have?

**Comment by 12rambau** [comment]
.jinja2

**Comment by 12rambau** [comment]
but I checked flask documentation and it seems commonly accepted to make it transparent

**Review by 12rambau — APPROVED** [review]

**Review by 12rambau — CHANGES_REQUESTED** [review]
putting this one on stale until #4 is merged

**Pull request merged**
